<?php
/**
 * Sigma SMS A2P — Configuration
 *
 * This file is auto-generated by install.php.
 * For Railway deployment, environment variables take precedence.
 */

// ── Database (Railway env vars override defaults) ────────────────────────────
define('DB_HOST',    getenv('MYSQLHOST')     ?: getenv('DB_HOST')  ?: 'localhost');
define('DB_PORT',    getenv('MYSQLPORT')     ?: getenv('DB_PORT')  ?: '3306');
define('DB_NAME',    getenv('MYSQLDATABASE') ?: getenv('DB_NAME')  ?: 'sigma_sms_a2p');
define('DB_USER',    getenv('MYSQLUSER')     ?: getenv('DB_USER')  ?: 'root');
define('DB_PASS',    getenv('MYSQLPASSWORD') ?: getenv('DB_PASS')  ?: '');
define('DB_CHARSET', 'utf8mb4');

// ── Application ──────────────────────────────────────────────────────────────
define('APP_NAME',    'Sigma SMS A2P');
define('APP_VERSION', '1.0.0');

// Detect APP_URL: env var > config > auto-detect
if (!defined('APP_URL')) {
    $appUrlEnv = getenv('APP_URL') ?: '';
    if ($appUrlEnv) {
        define('APP_URL', rtrim($appUrlEnv, '/'));
    } else {
        // Auto-detect for Railway / local
        $proto = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
        $host  = $_SERVER['HTTP_HOST'] ?? 'localhost';
        $path  = rtrim(dirname($_SERVER['PHP_SELF'] ?? '/'), '/\\');
        // If running from project root (Railway), path will be empty or /
        if ($path === '' || $path === '/' || $path === '\\') {
            define('APP_URL', "$proto://$host");
        } else {
            define('APP_URL', "$proto://$host$path");
        }
    }
}

// ── OTP API ──────────────────────────────────────────────────────────────────
define('OTP_API_URL',        'https://tempnum.net/api/public/otps');
define('OTP_FETCH_INTERVAL', 60); // minimum seconds between fetches

// ── Session ──────────────────────────────────────────────────────────────────
define('SESSION_LIFETIME', 86400); // 24 hours

// ── Timezone ─────────────────────────────────────────────────────────────────
date_default_timezone_set('UTC');

// ── Error reporting ──────────────────────────────────────────────────────────
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// ── PDO Database connection (singleton) ──────────────────────────────────────
function getDB(): PDO {
    static $pdo = null;
    if ($pdo === null) {
        $dsn = 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET;
        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ];
        try {
            $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            http_response_code(500);
            // Don't expose DB details in error output
            die(json_encode(['error' => 'Database connection failed. Check your configuration.']));
        }
    }
    return $pdo;
}

// ── Session initialization ───────────────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    $isSecure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
             || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https'); // Railway proxy
    session_set_cookie_params([
        'lifetime' => SESSION_LIFETIME,
        'path'     => '/',
        'secure'   => $isSecure,
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}
